### ISSUE TITLE
tf lite interpreter.h error

### ISSUE THREAD

**Issue by gorkemgul** [Qengineering/TensorFlow_Lite-Tracking-RPi_64-bit#1]
Hello, 

I've been trying and working on whole tracking models for a while. But when I jump into working with TensorFlow Lite Tracking. I got an error called: 
"fatal error: tensorflow/lite/interpreter.h No such file or directory" 

I looked for a solution on StackOverflow to fix this problem. Most of them were about eigen. I've tried many solutions so far, however, I could not fix this problem yet. If you would help me to fix this problem it would be appreciated.

Best Regards,

![error (2)](https://user-images.githubusercontent.com/104680758/208911683-0880b6be-2d1d-446e-9e79-41a5cd733c25.png)

**Comment by Qengineering** [comment]
Dear @gorkemgul,

Before you compile the code, you must have downloaded a full version of TensorFlow and build the TensorFlow Lite library. As you can see in the code, the header file is located at `<your install TF folder>/tensorflow/lite/interpreter.h`
Note also that there are other headers needed, all living in the lite folder.

Tip: Use TensorFlow 2.6. Our website and guides uses this somewhat older version. After version 2.6, Tensorflow has changed its strategy about the C++ implementation. Instead of a simple script, and one library, you now have to face a complex compilation session and lots of separate files. Depending on your app, some of these files need to be included. Not an easy job if you just start coding.

For further info see [Hands on section](https://qengineering.eu/deep-learning-examples-on-raspberry-32-64-os.html) and [OpenCV C++ examles](https://qengineering.eu/opencv-c-examples-on-raspberry-pi.html).

**Comment by gorkemgul** [comment]
First of all, Thanks for replying swiftly, 

Secondly, At first, I was using my own img which was given a lot of errors and I could not fix that. 

Then I downloaded the image you published on GitHub. Also, I was using instructions from "Hands on section" and "OpenCV C++ Examples". 

After you gave an answer about file paths. I realized that even if I was using your image, I needed to fix cbp file because my tensorflow folder wasn't named as tensorflow-2.6.0. After I did that I solved the tensorflow problem. 

Finally, another error occurred about eigen then I thought that it could be another file path problem and I found the file path of its using "find . -name "eigen*" -type d". After I changed its file path in cbp file, It worked. Now there's not any problem left.
